# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
org = "ballerinax"
name = "zipkin"
version = "0.8.1"
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/zipkin-extension-native-0.8.1.jar"
groupId = "ballerina"
artifactId = "zipkin-extension-native"
version = "0.8.1"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-exporter-zipkin-1.0.0.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-exporter-zipkin"
version = "1.0.0"

[[platform.java17.dependency]]
path = "./lib/zipkin-2.24.0.jar"
groupId = "io.zipkin.zipkin2"
artifactId = "zipkin"
version = "2.24.0"

[[platform.java17.dependency]]
path = "./lib/zipkin-reporter-2.16.0.jar"
groupId = "io.zipkin.reporter2"
artifactId = "zipkin-reporter"
version = "2.16.0"

[[platform.java17.dependency]]
path = "./lib/zipkin-sender-okhttp3-2.16.0.jar"
groupId = "io.zipkin.reporter2"
artifactId = "zipkin-sender-okhttp3"
version = "2.16.0"

[[platform.java17.dependency]]
path = "./lib/okio-jvm-3.5.0.jar"
groupId = "com.squareup.okio"
artifactId = "okio"
version = "3.5.0"

[[platform.java17.dependency]]
path = "./lib/okhttp-4.11.0.jar"
groupId = "com.squareup.okhttp3"
artifactId = "okhttp"
version = "4.11.0"

[[platform.java17.dependency]]
path = "./lib/kotlin-runtime-1.2.71.jar"
groupId = "org.jetbrains.kotlin"
artifactId = "kotlin-runtime"
version = "1.2.71"

[[platform.java17.dependency]]
path = "./lib/kotlin-stdlib-1.8.22.jar"
groupId = "org.jetbrains.kotlin"
artifactId = "kotlin-stdlib"
version = "1.8.22"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-api-metrics-1.0.0-alpha.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-api-metrics"
version = "1.0.0-alpha"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-sdk-trace-1.0.0.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-trace"
version = "1.0.0"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-sdk-common-1.0.0.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-sdk-common"
version = "1.0.0"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-semconv-1.0.0-alpha.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-semconv"
version = "1.0.0-alpha"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-proto-1.0.0-alpha.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-proto"
version = "1.0.0-alpha"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-exporter-otlp-trace-1.0.0.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-exporter-otlp-trace"
version = "1.0.0"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-exporter-otlp-common-1.0.0.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-exporter-otlp-common"
version = "1.0.0"

[[platform.java17.dependency]]
path = "./lib/opentelemetry-extension-trace-propagators-1.0.0.jar"
groupId = "io.opentelemetry"
artifactId = "opentelemetry-extension-trace-propagators"
version = "1.0.0"

[[platform.java17.dependency]]
path = "./lib/guava-32.1.2-jre.jar"
groupId = "com.google.guava"
artifactId = "guava"
version = "32.1.2-jre"

[[platform.java17.dependency]]
path = "./lib/failureaccess-1.0.1.jar"
groupId = "com.google.guava"
artifactId = "failureaccess"
version = "1.0.1"
